version: '3.9'
services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
  redis:
    image: redis:7.2.4
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
volumes:
  cache:
    driver: local
  
